### PR TITLE
extend timeout to 60 minutes and introduce timeout flag

### PR DESCRIPTION
**Pull request by NiklasTR**

### CODE REVIEW

**Comment by thetechnocrat-dev** [comment]
Will this also required a server side change on the `bacalhau serve` command?

**Review by thetechnocrat-dev — COMMENTED** [review]
We decide to move this to release v0.5.0, since this week is focused on equibind+oddt. 

Add directions for us to test.

**Review by thetechnocrat-dev — CHANGES_REQUESTED** [review]
We decide to move this to release v0.5.0, since this week is focused on equibind+oddt. 

Add directions for us to test.

Also, this only update the bacalhau -dry=true, not running bacalhau through plex. Change this function too: https://github.com/labdao/plex/blob/main/internal/bacalhau/bacalhau.go#L27

**Comment by NiklasTR** [comment]
Closing this issue with https://github.com/bacalhau-project/bacalhau/issues/2561 on the horizon

**Pull request closed without merging**
