### PR TITLE
update bacalhau

### PR DESCRIPTION
**Pull request by thetechnocrat-dev**
Loom video below. Bacal update seems to fix download issues. Updates also allowed a much simpler `GetBacalhauJobResults` function.

### CODE REVIEW

**Comment by thetechnocrat-dev** [comment]
https://www.loom.com/share/27f10ac2cca84894b137d5213c1e8c67

**Comment by acashmoney** [comment]
@NiklasTR can you test this? I tested and job timed out. Steps below to reproduce.

1) Create fresh directory
2) Clone repo
3) `go build`
4) `export WEB3STORAGE_TOKEN=<token value>`
5) `./plex -app equibind -input-dir ./testdata/binding/`

Before we merge this, we'll both want to make sure jobs are completing.

**Review by NiklasTR — APPROVED** [review]

**Comment by NiklasTR** [comment]
Hi @acashmoney  - the problem you describe is due to the pinning issue we have been working on. If you specify the input path as ```testdata/binding/pdbind_processed1``` you should be all set.

Hi @thetechnocrat-dev - this looks great. Thank you. 
I wonder wether we are able to supress the IPFS Ressource Manager limit notification: 
```
(base) rindtorff@niklas plex % ./plex -app equibind -input-dir ./testdata/binding/pdbbind_processed_size1
## User input ##
Provided application name: equibind
Provided directory path: ./testdata/binding/pdbbind_processed_size1
Using GPU: false
Using Network: false
## Default parameters ##
Using app configs: config/app.jsonl
Setting layers to: 2
## Validating ##
App found: equibind
## Searching input files ##
Found 2 matching files
testdata/binding/pdbbind_processed_size1/6d08/6d08_ligand.sdf
testdata/binding/pdbbind_processed_size1/6d08/6d08_protein_processed.pdb
Created job directory /Users/rindtorff/github/labdao/plex/9c1ac853-6ee4-449f-b5fd-1d444669312f
Uploading to IPFS via web3.storage... 
CID: bafybeibuivbwkakim3hkgphffaipknuhw4epjfu3bstvsuv577spjhbvju
## Creating Bacalhau Job ##
Bacalhau Job Id: 663960b9-cc07-4225-b707-bfc048d0b64f
Job running...
////_🌱___////
Computing default go-libp2p Resource Manager limits based on:
    - 'Swarm.ResourceMgr.MaxMemory': "8.6 GB"
    - 'Swarm.ResourceMgr.MaxFileDescriptors': 30720

Applying any user-supplied overrides on top.
Run 'ipfs swarm limit all' to see the resulting limits.


Your job results have been downloaded to /Users/rindtorff/github/labdao/plex/9c1ac853-6ee4-449f-b5fd-1d444669312f
```

**Comment by acashmoney** [comment]
Thank you @NiklasTR - the CID for the whole folder is unfamiliar to Bacalhau and results in slow uptake of input data. @thetechnocrat-dev approving these changes now

```
 aakaash@Aakaashs-MacBook-Pro  ~/Desktop/code/garage/fresh-plex/plex   108-ipfs-connection-error-when-retrieving-results  ./plex -app equibind -input-dir ./testdata/binding/pdbbind_processed_size1
## User input ##
Provided application name: equibind
Provided directory path: ./testdata/binding/pdbbind_processed_size1
Using GPU: false
Using Network: false
## Default parameters ##
Using app configs: config/app.jsonl
Setting layers to: 2
## Validating ##
App found: equibind
## Searching input files ##
Found 2 matching files
testdata/binding/pdbbind_processed_size1/6d08/6d08_ligand.sdf
testdata/binding/pdbbind_processed_size1/6d08/6d08_protein_processed.pdb
Created job directory /Users/aakaash/Desktop/code/garage/fresh-plex/plex/9a3bda52-8a27-4384-8746-ea68ff8c6bc6
Uploading to IPFS via web3.storage...
CID: bafybeibuivbwkakim3hkgphffaipknuhw4epjfu3bstvsuv577spjhbvju
## Creating Bacalhau Job ##
Bacalhau Job Id: 6fe9a9df-557a-4f27-9829-7680aceef376
Job running...
////_🌱___////
Computing default go-libp2p Resource Manager limits based on:
    - 'Swarm.ResourceMgr.MaxMemory': "8.6 GB"
    - 'Swarm.ResourceMgr.MaxFileDescriptors': 30720

Applying any user-supplied overrides on top.
Run 'ipfs swarm limit all' to see the resulting limits.

Your job results have been downloaded to /Users/aakaash/Desktop/code/garage/fresh-plex/plex/9a3bda52-8a27-4384-8746-ea68ff8c6bc6
```

**Comment by NiklasTR** [comment]
merging this

**Pull request merged**
