### PR TITLE
Update instruction_template.jsonl

### PR DESCRIPTION
**Pull request by NiklasTR**

### CODE REVIEW

**Comment by NiklasTR** [comment]
currently fails with

```
DGL backend not selected or invalid.  Assuming PyTorch for now.
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    predict(args)
  File "main.py", line 66, in predict
    inference_VS_2.multi_lig_inference(args)
  File "/src/inference_VS_2.py", line 488, in multi_lig_inference
    if not lig_name.endswith('.sdf'): raise ValueError('Multi-Ligand can only accept files in the sdf file format.')
ValueError: Multi-Ligand can only accept files in the sdf file format.
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    predict(args)
  File "main.py", line 66, in predict
    inference_VS_2.multi_lig_inference(args)
  File "/src/inference_VS_2.py", line 488, in multi_lig_inference
    if not lig_name.endswith('.sdf'): raise ValueError('Multi-Ligand can only accept files in the sdf file format.')
ValueError: Multi-Ligand can only accept files in the sdf file format.
```

We might have the following options: 
- [ ] mol2 to sdf converter
- [ ] QC module for sdf
- [ ] changing the input function call for equibind (probably easiest)

**Comment by thetechnocrat-dev** [comment]
Any updates on this PR?

**Comment by NiklasTR** [comment]
would leave open for now as we are upgrading instructions for 0.5

**Comment by thetechnocrat-dev** [comment]
Stale

**Pull request closed without merging**
